export const systems = [
  {
    id: 'nova-prime',
    name: 'NOVA PRIME',
    kind: 'Home system',
    coordinates: '084.32 / 029.71',
    position: [4.1, 0.25, 0],
    radius: 2.7,
    color: '#8097a4',
    accent: '#a5e9ef',
    threshold: 0,
    description:
      'A quiet world on the edge of possibility. Your home among the stars.',
    destination: 'GALAXY',
  },
  {
    id: 'solaris',
    name: 'SOLARIS',
    kind: 'Energy core',
    coordinates: '012.81 / 067.20',
    position: [-2.8, 3.5, -7],
    radius: 0.72,
    color: '#eaa565',
    accent: '#f8c58e',
    threshold: 0,
    description:
      'An ancient star. A new kind of currency. Discover the energy that powers your journey.',
    destination: 'TOKEN',
  },
  {
    id: 'asteroid-belt',
    name: 'ASTEROID BELT',
    kind: 'Combat sector',
    coordinates: '092.16 / 038.02',
    position: [-3.0, -1.65, 1],
    radius: 0.4,
    color: '#a3a2a2',
    accent: '#e6b385',
    threshold: 0,
    description:
      'Debris fields. Rogue drones. A frontier worth defending. Your next mission starts here.',
    destination: 'GAME',
  },
  {
    id: 'nebula-7',
    name: 'NEBULA–7',
    kind: 'Orbital vault',
    coordinates: '064.07 / 091.33',
    position: [0.1, 3.4, -5],
    radius: 0.47,
    color: '#8692cd',
    accent: '#bdc0ff',
    threshold: 0,
    description:
      'Your rewards, safely in orbit. Every discovery leaves something behind.',
    destination: 'WALLET',
  },
  {
    id: 'void-sector',
    name: 'VOID SECTOR',
    kind: 'Deep space',
    coordinates: '137.42 / 008.16',
    position: [8.4, 3, -6],
    radius: 0.64,
    color: '#679b9b',
    accent: '#8ae8cc',
    threshold: 1000,
    description:
      'Beyond the familiar routes. Earn 1,000 lifetime NOVA to chart this system.',
    destination: 'PLANET',
  },
  {
    id: 'echo-station',
    name: 'ECHO STATION',
    kind: 'Explorer archive',
    coordinates: '029.20 / 048.62',
    position: [9.2, -2.8, -2],
    radius: 0.27,
    color: '#cadad2',
    accent: '#c4fbdf',
    threshold: 0,
    description:
      'A small station with a long memory. Every flight has a story.',
    destination: 'LEADERBOARD',
    model: 'station',
  },
  {
    id: 'atlas-relay',
    name: 'ATLAS RELAY',
    kind: 'Galaxy map',
    coordinates: '041.09 / 003.85',
    position: [-0.5, -3.4, -3],
    radius: 0.2,
    color: '#97bfbc',
    accent: '#c4eadc',
    threshold: 0,
    description:
      'An invitation to see the bigger picture. Chart a course to your next discovery.',
    destination: 'MAP',
    model: 'station',
  },
  {
    id: 'voyager',
    name: 'VOYAGER–01',
    kind: 'About the universe',
    coordinates: '048.22 / 032.09',
    position: [4.4, 5, -9],
    radius: 0.18,
    color: '#949cae',
    accent: '#b2c7dd',
    threshold: 0,
    description:
      'A message from the makers. For the part of you that still looks up.',
    destination: 'ABOUT',
    model: 'portal',
  },
];

export const cameraConfig = {
  duration: 1.6,
  INTRO: { position: [0, 0.9, 20], target: [0, 0, 0] },
  GALAXY: { position: [0, 0.9, 18.5], target: [0, 0, 0] },
  GAME: { position: [0, 0, 16], target: [0, 0, -8] },
  MAP: { position: [0, 6, 24], target: [0.4, 0, -1] },
  WALLET: { position: [0, 1.8, 20], target: [0.5, 0, 0] },
  TOKEN: { position: [-3, 2, 19], target: [-1, 0.5, -2] },
  ABOUT: { position: [0, 1, 20], target: [0, 0, 0] },
  LEADERBOARD: { position: [3, 0.2, 19], target: [1, 0, -1] },
};
